import { jsPDF } from 'jspdf';

export const generateDummyPDF = (): Blob => {
  const doc = new jsPDF();
  
  // Add title
  doc.setFontSize(20);
  doc.text('Frigg\'s Gate Sample Document', 20, 30);
  
  // Add subtitle
  doc.setFontSize(14);
  doc.text('Life Nervous System - Document Preview Demo', 20, 45);
  
  // Add some content
  doc.setFontSize(12);
  const content = [
    'This is a sample PDF document generated for Frigg\'s Gate.',
    '',
    'Key Features:',
    '• In-browser PDF preview using PDF.js',
    '• Downloadable file support',
    '• ChatGPT-style overlay interface',
    '• Forward-compatible architecture for real documents',
    '',
    'The Life Nervous System (LNS) provides cognitive interface',
    'capabilities with structured input/output workspace coordination.',
    '',
    'This document demonstrates the file attachment and preview',
    'functionality that will be extended to support user uploads',
    'and AI analysis of documents.',
    '',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    'Sed do eiusmod tempor incididunt ut labore et dolore magna',
    'aliqua. Ut enim ad minim veniam, quis nostrud exercitation',
    'ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    '',
    'For more information, visit the Frigg\'s Gate repository.'
  ];
  
  let yPosition = 60;
  content.forEach(line => {
    if (line === '') {
      yPosition += 6;
    } else {
      doc.text(line, 20, yPosition);
      yPosition += 8;
    }
  });
  
  // Add footer
  doc.setFontSize(10);
  doc.text('Generated by Frigg\'s Gate - ' + new Date().toLocaleDateString(), 20, 280);
  
  return doc.output('blob');
};

export const createPDFDownloadLink = (blob: Blob, filename: string = 'friggs-gate-sample.pdf'): string => {
  const url = URL.createObjectURL(blob);
  return url;
};